usb: gadget: Fix missing hidg_hs_out_ep_desc declaration
Missing declaration results in the following compilation error:

drivers/usb/gadget/f_hid.c: In function 'hidg_bind':
/drivers/usb/gadget/f_hid.c:563:2: error: 'hidg_hs_out_ep_desc' undeclared (first use in this function)
  hidg_hs_out_ep_desc.bEndpointAddress =
  ^
/drivers/usb/gadget/f_hid.c:563:2: note: each undeclared identifier is reported only once for each function it appears in
/drivers/usb/gadget/f_hid.c:564:3: error: 'hidg_fs_out_ep_desc' undeclared (first use in this function)
   hidg_fs_out_ep_desc.bEndpointAddress;
   ^
  CC      drivers/staging/prima/CORE/MAC/src/pe/lim/limAIDmgmt.o
make[4]: *** [/scripts/Makefile.build:308: drivers/usb/gadget/f_hid.o] Error 1
make[3]: *** [/scripts/Makefile.build:443: drivers/usb/gadget] Error 2

Signed-off-by: Re4son <re4son@users.noreply.github.com>
Change-Id: I861cc8c37c2df5d0d47cbc30b218428498d2fbf6